# Generated by Django 3.2.5 on 2021-07-06 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_first_name_author_f_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='f_name',
            new_name='first_name',
        ),
    ]
